version: '2'
services:
    hipstagram-app:
        image: hipstagram
        external_links:
            - hipstagram-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hipstagram
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hipstagram-postgresql:
        extends:
            file: postgresql.yml
            service: hipstagram-postgresql
